apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert -o ./k8s/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: logic
  name: logic
spec:
  type: NodePort 
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    io.kompose.service: logic
status:
  loadBalancer: {}
